// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007150800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fulfillment_status", new[] { "unfulfilled", "processing", "shipped", "delivered", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", new[] { "pending", "paid", "failed", "cancelled", "refunded", "partially_refunded", "disputed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Entities.StripeEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StripeEvents");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b8d4a1c-5b85-4a27-934f-4f6c76f2e501"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Electronics",
                            Slug = "electronics",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8f0a7df6-22c2-4900-8e47-b3d2d6be8bc6"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Books",
                            Slug = "books",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d4c2d79d-b3c3-4b26-85e8-dad8f89dbcd1"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kitchen",
                            Slug = "kitchen",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0e6ccf6-555b-48c8-b4e6-26826a464e26"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stationery",
                            Slug = "stationery",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ec0d92a8-8ec8-4d21-8d2e-29c2f9c38430"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Toys",
                            Slug = "toys",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("FulfillmentStatus")
                        .HasColumnType("fulfillment_status");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ShippingAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingPhone")
                        .HasColumnType("text");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingState")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("order_status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f623603-229d-40ac-a52f-5c040efb174a"),
                            CategoryId = new Guid("2b8d4a1c-5b85-4a27-934f-4f6c76f2e501"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            Description = "256GB · 6.7\" AMOLED · 5G",
                            IsActive = true,
                            Price = 999m,
                            StockQuantity = 8,
                            Title = "Nexora One X",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 1, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bc224020-0bf0-4eb4-88b2-1fe2b0408a86"),
                            CategoryId = new Guid("2b8d4a1c-5b85-4a27-934f-4f6c76f2e501"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            Description = "14\" 2.8K · 16GB RAM · 512GB SSD",
                            IsActive = true,
                            Price = 899m,
                            StockQuantity = 6,
                            Title = "AeroBook 14",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 2, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cf578350-5640-4d0e-b676-1fc32b6c0c83"),
                            CategoryId = new Guid("2b8d4a1c-5b85-4a27-934f-4f6c76f2e501"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 3, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless · Noise cancelling · 50h",
                            IsActive = true,
                            Price = 249m,
                            StockQuantity = 3,
                            Title = "Pulse ANC Pro",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 3, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1303f95d-a3b1-4697-8721-72c624d7e9e9"),
                            CategoryId = new Guid("2b8d4a1c-5b85-4a27-934f-4f6c76f2e501"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 4, 0, 0, DateTimeKind.Utc),
                            Description = "15.6\" QHD · RTX-class graphics · 16GB RAM",
                            IsActive = true,
                            Price = 1299m,
                            StockQuantity = 5,
                            Title = "Volt G15",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 4, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5d6ab7cc-d3d1-434b-bd74-8f388ff04cf7"),
                            CategoryId = new Guid("8f0a7df6-22c2-4900-8e47-b3d2d6be8bc6"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            Description = "A hands-on guide to memory, processes and the kernel.",
                            IsActive = true,
                            Price = 34.99m,
                            StockQuantity = 12,
                            Title = "Systems Programming in C",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("245ad70d-64e3-4721-b73a-d6adc324f1bb"),
                            CategoryId = new Guid("d4c2d79d-b3c3-4b26-85e8-dad8f89dbcd1"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 6, 0, 0, DateTimeKind.Utc),
                            Description = "Pre-seasoned skillet for the stove and the oven.",
                            IsActive = true,
                            Price = 34.99m,
                            StockQuantity = 15,
                            Title = "Cast Iron Skillet 10in",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 6, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ff7715c2-3e0a-4229-8b8d-a4de405d3ca8"),
                            CategoryId = new Guid("a0e6ccf6-555b-48c8-b4e6-26826a464e26"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 7, 0, 0, DateTimeKind.Utc),
                            Description = "160 pages of 100gsm paper with a lay-flat spine.",
                            IsActive = true,
                            Price = 12.99m,
                            StockQuantity = 40,
                            Title = "Dot Grid Notebook A5",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 7, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eb52a79a-de3b-48e3-bced-93c9335e3949"),
                            CategoryId = new Guid("ec0d92a8-8ec8-4d21-8d2e-29c2f9c38430"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 8, 0, 0, DateTimeKind.Utc),
                            Description = "100 smooth beechwood blocks in a cotton bag.",
                            IsActive = true,
                            Price = 24.99m,
                            StockQuantity = 25,
                            Title = "Wooden Building Blocks Set",
                            UpdatedAt = new DateTime(2026, 10, 1, 0, 8, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Cart", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.CartItem", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ecommerce.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Order", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ecommerce.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("PasswordResetTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
